### ISSUE TITLE
הצעה למונחים

### ISSUE THREAD

**Issue by roysharon** [ChavaScript/chavascript#15]
‫קודם כל ברכות על הרעיון והמימוש! נחמד מאד.

‫לא יודע אם אתם עדיין שוקלים שינויים במונחים, אבל אם כן אז שתי הצעות לשינויים/תוספות במונחים:
1. במקום ״כלעוד״ אפשר ״כאשר״.
2. במקום ״לאמוגדר״ אפשר ״תוהו״.

אם לא מתאים פשוט תסגרו את הטיקט הזה.
בכל מקרה תודה על היצירתיות ששעשעה אותי השבת. 🙏

**Comment by avivcarmis** [comment]
כן מתאים  😄 נשמע יותר הגיוני מילה אחת עבור מילים שמורות. השינוי הוא מאוד קצר ופשוט, אבל כדי לעדכן את הדוקומנטציה הייתי מציע פשוט לעשות
search & replace
על הריפו כולו. תרגיש חופשי לפתוח
pull request
אם בא לך לתרום, אם לא, אגיע לזה בקרוב
תודה על ההצעה 🙏
