### ISSUE TITLE
אי טיפול בסוגריים המסולסלים

### ISSUE THREAD

**Issue by osher** [ChavaScript/chavascript#21]
הייתי מצפה שיטופלו הסוגריים המסולסלות כמו שטופלו הסוגריים העגולות והמרובעות

האם יש כוונת מתכנן מאחורי זה, או שמא זו מגבלה טכנית?

**Comment by osher** [comment]
אוי ווי זמיר. זה כן מטופל.

זה אני התרגלתי לקרוא הפוך, וכעת זה נראה לי מוזר

**Comment by osher** [comment]
חחח. גם מבלבל ומעיק על הקריאה הכיוון אליו נוטה הפסיק בנקודה-פסיק

**Comment by avivcarmis** [comment]
@osher 😂  it is what it is, right-to-left sucks 😂 
Closing this one
