### ISSUE TITLE
תרגום חסר - סוג דובל?

### ISSUE THREAD

**Issue by osher** [ChavaScript/chavascript#22]
גם בשש בש זה לא מילה

אם כבר, אז כפול, או כפליים

אני לא אומר מילה על בוליאן, אלא אשב לבד בחושך.

**Comment by avivcarmis** [comment]
@osher 
האמת שבמקרה הזה אני נוטה לא להסכים. אמנם דובל היא לא מילה בעברית אבל פה נכנס כל הכיף של חווה. גם פנח״ס הוא לא התרגום המילולי של
JSON
ובכל זאת, אם ניקח את זה מה יישאר?
😂 
ברשותך אני אסגור את האישיו, אם נראה עוד אנשים נוספים נוטים בחוזקה לכיוון שלך יכול להיות שנשקול שוב?
בכל מקרה אני אשמח אם תמשיך להביע עמדה אם אתה מוצא עוד בעיות או דברים שאפשר לטעמך לשפר. תרגיש חופשי גם לפתוח
pull request
עם תיקונים ל
issues
אחרים
🙏
