### ISSUE TITLE
Correct translation for Reduce function

### ISSUE THREAD

**Issue by idosilverwater** [ChavaScript/chavascript#29]
The correct translation for the reducing function (reduce) is: צמצם
https://en.wikipedia.org/wiki/Fold_(higher-order_function)

**Comment by avivcarmis** [comment]
@idosilverwater I can go with that. Please open a pull request and I'll merge it.
You'll simply need to search and replace all occurrences of הפחת with צמצם 👍

**Comment by Matanoga** [comment]
+1 for "צמצם" 😄

**Comment by avivcarmis** [comment]
צומצמתם
