### ISSUE TITLE
Maybe Invalid Translation

### ISSUE THREAD

**Issue by eavichay** [ChavaScript/chavascript#31]
פרוייקט חמוד, חלק מהתרגום בעייתי בעיניי.
מעבר לעובדה שהפקודות הן בלשון נקבה מה שעלול לעורר מחשבות מכאן ומשם, כל אחד וגישתו הוא - אפשר לתרגם את הדברים לגירסה לא מגדרית.
בנוסף כיוון שמילות המפתח בשפה הן גילגול של שפות קודמות כמו שפת סי, אם המטרה היא להנגיש, אפשר למצוא מילים שהמשמעות שלהן יותר קרובה לביצוע בפועל

למשל

return -> יציאה / חזרה
switch -> בדיקה / מצב
break -> שבירה
continue -> המשך / הלאה
if-else -> אם / אחרת
try-catch-finally
ניסוי / טעיה / סיום או לבסוף
throw - שגיאה

class -> מחלקה בספרות, תרגום גרוע לדעתי, אולי טיפוס או סוג
function -> שגרה או פעולה

**Comment by avivcarmis** [comment]
@eavichay תודה על הפידבק
את הטיית המגדר בחווה סקריפט אנחנו רוצים כרגע לשמר, למעשה זה אחד הדברים המרכזיים שאני אישית אתעקש עליהם. לא הייתי רוצה שהפרויקט יפגע באף אחד אבל אם למישהו מתעוררות מחשבות לכאן או לכאן בעקבות הטייה ללשון נקבה, חווה מוסרת שהשפה הזאת לא בשבילו ❤️
