### ISSUE TITLE
Typo for warn

### ISSUE THREAD

**Issue by efratha94** [ChavaScript/chavascript#33]
בדוקומנטציה כתוב ש-warn מתורגם כ"אזהר", צריך להיות "הזהר" :)
אגב, מה עם async await?

**Comment by avivcarmis** [comment]
@efratha94 Nice catch 🤦‍♀️ i'll fix it now. As for async/await - open a [new issue](https://github.com/ChavaScript/chavascript/issues/37) so we can vote on new naming
